spring:
  application:
    name: messager
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/your_db_name
    username: your_db_user
    password: your_db_password

logging:
  level:
    org.springframework.amqp: DEBUG
